# Copyright (c) 2026 Control Plane Limited. All rights reserved.
# Built by ControlPlane for the FINOS OSERA Exchange.
# SPDX-License-Identifier: Apache-2.0
# The file a patch repository carries, .github/workflows/osera-fitness.yaml, on the patch branch.
# On push of a release tag it calls the OSERA fitness check library. Nothing else to configure.
name: OSERA fitness checks
run-name: OSERA fitness checks on ${{ github.ref_name }}

on:
  push:
    tags: ['v*\+osera-patch.*'] # the + must be escaped, GitHub treats it as a special character in tag filters

permissions:
  contents: read # for checking out the repository.
  id-token: write # for creating OIDC tokens for signing.
  attestations: write # for GitHub Attestations.

jobs:
  fitness:
    uses: d1gital-f/osera-fitness-checks/.github/workflows/fitness.yaml@v0.1.0
    with:
      tag: ${{ github.ref_name }}
      expected-org: d1gital-f
